version: "3.7"
services:
  backend:
    build: ./Spring-HelpQueue
    image: backend:latest
    container_name: backend
    ports:
    - target: 8081
      published: 8081
      protocol: tcp
    env_file:
      - .env
