apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: (dockerusername)/backend
        env:
        - name: DATABASE_URI #environment variable for security
          valueFrom:
            secretKeyRef:
              name: secretsql #name of secret
              key: DATABASE_URI
        - name: TEST_DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: secretsql
              key: TEST_DATABASE_URI
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secretsql
              key: SECRET_KEY
        ports:
        - containerPort: 8081
