---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: reeceelder/backend:latest
        env:
        - name: db_endpoint
          valueFrom:
            secretKeyRef:
              name: secretvar
              key: db_endpoint
        - name: password
          valueFrom:
            secretKeyRef:
              name: secretvar
              key: password
        - name: db_username
          valueFrom:
            secretKeyRef:
              name: secretvar
              key: db_username
        - name: testdb_username
          valueFrom:
            secretKeyRef:
              name: secretvar
              key: testdb_username
        - name: testdb_endpoint
          valueFrom:
            secretKeyRef:
              name: secretvar
              key: testdb_endpoint
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP
