apiVersion: v1
kind: Service
metadata:
  name: fe-nginx-lb
  labels:
    app: fe-nginx
spec: 
  selector: 
    app: fe-nginx
  ports: 
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer
