apiVersion: v1
kind: ConfigMap
metadata:
  name: fe-nginx-config
data:
  default.conf: |
      server {
          listen 80;
          location / {
              proxy_pass http://backendip:8081; 
          }
      }
      
    
