apiVersion: v1
kind: Secret
metadata:
  name: mysqlsecret
type: Opaque
stringData:
  DATABASE_URI: 'mysql+pymsql://username:password@endpoint:3306/#'
  SECRET_KEY: '#'
  TEST_DATABASE_URI: 'mysql+pymsql://username:password@endpoint:3306/#'
