---
- hosts: jenkins
  become: true
  vars:
    CTOP_VERSION: "0.7.3"
    DOCKER_COMPOSE_VERSION: "1.25.1"
    DOCKER_PACKAGES:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
  roles:
  - utilities
  - jenkins
  - kubernetes
  - sudo-doers
  - testvm_pub-key_to_jenkinsvm
    # - docker

- hosts: testvm
  become: true
  roles: 
  - utilities
  - sudo-doers
  - jenkinsvm_pub-key_to_testvm

